# Generated by Django 3.0.2 on 2020-01-31 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uploads',
            new_name='Upload',
        ),
    ]
